// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReWearWeb.Data;

#nullable disable

namespace ReWearWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReWearWeb.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Camisas casuales y formales",
                            Nombre = "Camisas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Jeans, pantalones casuales y formales",
                            Nombre = "Pantalones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Vestidos de todo tipo",
                            Nombre = "Vestidos"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Zapatillas, zapatos formales y casuales",
                            Nombre = "Zapatos"
                        });
                });

            modelBuilder.Entity("ReWearWeb.Models.Prenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstaDisponible");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Color = "Blanco",
                            Descripcion = "Camisa blanca de manga larga, talla M, pocas veces usada. Ideal para trabajo o eventos casuales.",
                            EstaDisponible = true,
                            Estado = "Usado - Bueno",
                            FechaPublicacion = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Zara",
                            Precio = 35.00m,
                            Talla = "M",
                            Titulo = "Camisa blanca de algodón",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Color = "Azul oscuro",
                            Descripcion = "Jeans azul oscuro, talla 32, corte recto. Muy cómodos y sin desgaste visible.",
                            EstaDisponible = true,
                            Estado = "Usado - Excelente",
                            FechaPublicacion = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Levi's",
                            Precio = 55.00m,
                            Talla = "32",
                            Titulo = "Jeans azul clásico",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Color = "Estampado",
                            Descripcion = "Vestido corto con estampado floral, material liviano. Perfecto para el verano.",
                            EstaDisponible = true,
                            Estado = "Nuevo con etiqueta",
                            FechaPublicacion = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Mango",
                            Precio = 48.00m,
                            Talla = "S",
                            Titulo = "Vestido floral de verano",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Color = "Blanco",
                            Descripcion = "Zapatillas blancas de cuero sintético, talla 40. Usadas solo un par de veces.",
                            EstaDisponible = true,
                            Estado = "Usado - Muy bueno",
                            FechaPublicacion = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Nike",
                            Precio = 80.00m,
                            Talla = "40",
                            Titulo = "Zapatillas blancas casuales",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Color = "Rojo/Negro",
                            Descripcion = "Camisa de franela a cuadros rojos y negros, estilo vintage.",
                            EstaDisponible = true,
                            Estado = "Usado - Bueno",
                            FechaPublicacion = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Hollister",
                            Precio = 42.00m,
                            Talla = "L",
                            Titulo = "Camisa a cuadros estilo vintage",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("ReWearWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "García López",
                            Email = "maria@rewear.pe",
                            FechaRegistro = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Password = "Rewear2024",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Ramírez Paz",
                            Email = "carlos@rewear.pe",
                            FechaRegistro = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Password = "Rewear2024",
                            Telefono = "912345678"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Torres Quispe",
                            Email = "ana@rewear.pe",
                            FechaRegistro = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Password = "Rewear2024",
                            Telefono = "955111222"
                        });
                });

            modelBuilder.Entity("ReWearWeb.Models.Prenda", b =>
                {
                    b.HasOne("ReWearWeb.Models.Categoria", "Categoria")
                        .WithMany("Prendas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReWearWeb.Models.Usuario", "Vendedor")
                        .WithMany("PrendasEnVenta")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ReWearWeb.Models.Categoria", b =>
                {
                    b.Navigation("Prendas");
                });

            modelBuilder.Entity("ReWearWeb.Models.Usuario", b =>
                {
                    b.Navigation("PrendasEnVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
